In [1]:
import numpy as np
import pandas as pd
import plotly
import plotly.figure_factory as ff
import plotly.graph_objs as go
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot
init_notebook_mode(connected=True)
from sklearn.linear_model import SGDClassifier

In [2]:
! gdown --id 1C-SWfumjJYqXJ1_8WzxUQ-pMsXdBLX9P

Downloading...
From: https://drive.google.com/uc?id=1C-SWfumjJYqXJ1_8WzxUQ-pMsXdBLX9P
To: /content/task_b.csv
100% 12.9k/12.9k [00:00<00:00, 21.2MB/s]


In [3]:
data = pd.read_csv('task_b.csv')
data=data.iloc[:,1:]

In [4]:
data.head()

f1            f2        f3    y
0  -195.871045 -14843.084171  5.532140  1.0
1 -1217.183964  -4068.124621  4.416082  1.0
2     9.138451   4413.412028  0.425317  0.0
3   363.824242  15474.760647  1.094119  0.0
4  -768.812047  -7963.932192  1.870536  0.0

In [5]:
data.corr()['y']

f1    0.067172
f2   -0.017944
f3    0.839060
y     1.000000
Name: y, dtype: float64

In [6]:
data.std()

f1      488.195035
f2    10403.417325
f3        2.926662
y         0.501255
dtype: float64

In [7]:
X=data[['f1','f2','f3']].values
Y=data['y'].values
print(X.shape)
print(Y.shape)

(200, 3)
(200,)


# What if our features are with different variance 

<pre>
* <b>As part of this task you will observe how linear models work in case of data having feautres with different variance</b>
* <b>from the output of the above cells you can observe that var(F2)>>var(F1)>>Var(F3)</b>

> <b>Task1</b>:
    1. Apply Logistic regression(SGDClassifier with logloss) on 'data' and check the feature importance
    2. Apply SVM(SGDClassifier with hinge) on 'data' and check the feature importance

> <b>Task2</b>:
    1. Apply Logistic regression(SGDClassifier with logloss) on 'data' after standardization 
       i.e standardization(data, column wise): (column-mean(column))/std(column) and check the feature importance
    2. Apply SVM(SGDClassifier with hinge) on 'data' after standardization 
       i.e standardization(data, column wise): (column-mean(column))/std(column) and check the feature importance

</pre>

<h3><font color='blue'> Make sure you write the observations for each task, why a particular feautre got more importance than others</font></h3>

# **Task 1** Applying linear models without standardissation

In [8]:
clf1=SGDClassifier(loss='log',random_state=1)
clf1.fit(X,Y)
imp=clf1.coef_
print(imp)
print('Featue importance:')
for i in range(len(imp[0])):
  print('Feature {} - {}'.format(i+1,imp[0][i]))

[[ 5267.18579434 -1261.46205297 10496.88792549]]
Featue importance:
Feature 1 - 5267.185794336612
Feature 2 - -1261.4620529663039
Feature 3 - 10496.887925492816


In [9]:
clf2=SGDClassifier(loss='hinge',random_state=1)
clf2.fit(X,Y)
imp2=clf2.coef_
print(imp2)
print('Featue importance:')
for i in range(len(imp2[0])):
  print('Feature {} - {}'.format(i+1,imp2[0][i]))

[[ 4045.45902552  -325.5178316  10565.3285674 ]]
Featue importance:
Feature 1 - 4045.4590255220182
Feature 2 - -325.5178316017795
Feature 3 - 10565.32856739803


# **Observation**
In the above task we can see that high variance of features afftecting the model. From the above task we can see that, with increase in the variance of the feature, the feature importanceof corresponding feature is decreasing. In both the cases either using model linear SVM or Logistic regression, we get the following result:
1. Feature 2 has the highest variance but its feature importance is lowest.
2. Feature 3 has the lowest variance but its feature importance is highest.

# **Task 2** Applying linear models after standardisation

In [10]:
std=StandardScaler()
x_std=std.fit_transform(X)
clf1.fit(x_std,Y)
imp3=clf1.coef_
print(imp3)
print('Featue importance:')
for i in range(len(imp3[0])):
  print('Feature {} - {}'.format(i+1,imp3[0][i]))

[[5.80624985e-03 3.04119874e+00 1.47823461e+01]]
Featue importance:
Feature 1 - 0.00580624984797021
Feature 2 - 3.041198735618115
Feature 3 - 14.78234608580175


In [11]:
clf2.fit(x_std,Y)
imp4=clf2.coef_
print(imp4)
print('Featue importance:')
for i in range(len(imp4[0])):
  print('Feature {} - {}'.format(i+1,imp4[0][i]))

[[-11.32845251  -3.77762002  32.92573329]]
Featue importance:
Feature 1 - -11.328452510082409
Feature 2 - -3.777620022475722
Feature 3 - 32.9257332867221


# **Observation :**
In the above task when we standardised the data, we can see that the problem of high variance is eradicated now. Now the feature importance is not dependent on variance of the feature. Now we got to know that linear models are highly sensitive to variance or std. deviation, so it is important to always standardize your data before training the model with it.